### PR TITLE
[WIP]:Add structure for docs based on Julia docs

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Comment by henrykironde** [comment]
@ShivamNegi, feel free to look through and test. Edit as you wish.

So far the docs string are not utilized

In the doc folder use 
julia --color=yes make.jl
or 
julia make.jl

**Comment by ShivamNegi** [comment]
Wow! Looks great.

**Comment by henrykironde** [comment]
@ShivamNegi what do you think about the naming conversion of the project name and the module name. I think we are missing something. Most of the packages have Capital letters using the Camel style. 
I have not checked well but I think you have a more clear idea.

**Comment by ShivamNegi** [comment]
You are right. [Julia docs](https://docs.julialang.org/en/release-0.4/manual/style-guide/) also mention Camel style. I will take up updating the naming. :+1:

**Comment by henrykironde** [comment]
I did that. Currently I am trying to get the docs to build well. All the md files build.
The source code does not. I mean we are not getting the docstrings. Please have a look into that.

Either there is something wrong with the docstrings or we are missing out something

**Comment by henrykironde** [comment]
@ShivamNegi, you can check the structure here. I think this PR has the right structure. The only think remaining is to make sure the docstrings are built. 

The docstrings we have are not in the right form.

**Pull request merged**
